# Generated by Django 4.2.16 on 2026-08-07 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='景点名称')),
                ('cover', models.CharField(max_length=500, verbose_name='封面图URL')),
                ('images', models.TextField(blank=True, default='', verbose_name='图片URL列表(JSON)')),
                ('description', models.TextField(verbose_name='景点介绍')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='位置')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='门票价格')),
                ('open_time', models.CharField(blank=True, max_length=100, verbose_name='开放时间')),
                ('rating', models.FloatField(default=5.0, verbose_name='评分')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('is_hot', models.BooleanField(default=False, verbose_name='热门推荐')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='精选推荐')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '景点',
                'verbose_name_plural': '景点',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('icon', models.CharField(blank=True, max_length=500, verbose_name='图标URL')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '景点分类',
                'verbose_name_plural': '景点分类',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('avatar', models.CharField(blank=True, max_length=500, verbose_name='头像URL')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('rating', models.IntegerField(default=5, verbose_name='评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tourism.attraction', verbose_name='景点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.CharField(max_length=500, verbose_name='图片URL')),
                ('link_type', models.CharField(default='attraction', max_length=20, verbose_name='跳转类型')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('attraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourism.attraction', verbose_name='关联景点')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'ordering': ['sort'],
            },
        ),
        migrations.AddField(
            model_name='attraction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attractions', to='tourism.category', verbose_name='分类'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='tourism.attraction', verbose_name='景点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'unique_together': {('user', 'attraction')},
            },
        ),
    ]
