# Generated by Django 4.2.16 on 2026-08-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='cover',
            field=models.CharField(max_length=2000, verbose_name='封面图URL'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.CharField(max_length=2000, verbose_name='图片URL'),
        ),
    ]
